In [1]:
import pandas as pd
import pylab
import sklearn as sk
%pylab inline

df = pd.read_csv('./data/card_transdata.csv')

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


/usr/local/lib/python3.8/dist-packages/IPython/core/magics/pylab.py:162: UserWarning: pylab import has clobbered these variables: ['pylab']
`%matplotlib` prevents importing * from pylab and numpy
  warn("pylab import has clobbered these variables: %s"  % clobbered +


In [2]:
from sklearn.model_selection import train_test_split

#divide the dataset into train and test data set

#divide target class and the rest of features
X = df.drop("fraud", axis=1)
y = df["fraud"]

#divide the dataset into train and test data set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=22, stratify=y)

In [3]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import recall_score
from sklearn.metrics import confusion_matrix

In [4]:
X[:10]
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 7 columns):
 #   Column                          Non-Null Count    Dtype  
---  ------                          --------------    -----  
 0   distance_from_home              1000000 non-null  float64
 1   distance_from_last_transaction  1000000 non-null  float64
 2   ratio_to_median_purchase_price  1000000 non-null  float64
 3   repeat_retailer                 1000000 non-null  float64
 4   used_chip                       1000000 non-null  float64
 5   used_pin_number                 1000000 non-null  float64
 6   online_order                    1000000 non-null  float64
dtypes: float64(7)
memory usage: 53.4 MB


In [5]:
%%time
# train the MultinomialNB model 
nb_model = MultinomialNB().fit(X_train, y_train)

CPU times: user 129 ms, sys: 170 ms, total: 299 ms
Wall time: 296 ms


In [6]:
%%time
# train the DecisionTree model 
dt_model = DecisionTreeClassifier().fit(X_train, y_train)

CPU times: user 2.05 s, sys: 57.2 ms, total: 2.11 s
Wall time: 2.08 s


In [7]:
%%time
# train the RandomForest model 
rf_model = RandomForestClassifier().fit(X_train, y_train)

CPU times: user 1min 4s, sys: 1.28 s, total: 1min 5s
Wall time: 1min 6s


In [8]:
%%time
# MultinomialNB model prediction
nb_preds = nb_model.predict(X_test)

CPU times: user 305 ms, sys: 23.1 ms, total: 328 ms
Wall time: 42.1 ms


In [9]:
%%time
# MultinomialNB model prediction
dt_preds = dt_model.predict(X_test)

CPU times: user 60.5 ms, sys: 484 µs, total: 60.9 ms
Wall time: 7.4 ms


In [10]:
%%time
# MultinomialNB model prediction
rf_preds = rf_model.predict(X_test)

CPU times: user 1.57 s, sys: 308 µs, total: 1.57 s
Wall time: 732 ms


In [11]:
#recall of each model
nb_recall = recall_score(y_test, nb_preds, pos_label=0)
dt_recall = recall_score(y_test, dt_preds, pos_label=0)
rf_recall = recall_score(y_test, rf_preds, pos_label=0)

print(f"nb_recall = {nb_recall}")
print(f"dt_recall = {dt_recall}")
print(f"rf_recall = {rf_recall}")

nb_recall = 0.9793720105851994
dt_recall = 1.0
rf_recall = 1.0


In [12]:
# accuracy of each model
nb_accuracy = nb_model.score(X_test, y_test)
dt_accuracy = dt_model.score(X_test, y_test)
rf_accuracy = rf_model.score(X_test, y_test)

print(f"nb_accuracy = {nb_accuracy}")
print(f"dt_accuracy = {dt_accuracy}")
print(f"rf_accuracy = {rf_accuracy}")

nb_accuracy = 0.91979
dt_accuracy = 0.99997
rf_accuracy = 0.99998


In [13]:
nb_cm = confusion_matrix(y_test, nb_preds)
dt_cm = confusion_matrix(y_test, dt_preds)
rf_cm = confusion_matrix(y_test, rf_preds)

print(f"nb confusion matrix: \n {nb_cm}\n")
print(f"dt confusion matrix: \n {dt_cm}\n")
print(f"rf confusion matrix: \n {rf_cm}\n")

nb confusion matrix: 
 [[178754   3765]
 [ 12277   5204]]

dt confusion matrix: 
 [[182519      0]
 [     6  17475]]

rf confusion matrix: 
 [[182519      0]
 [     4  17477]]

