In [100]:
import pandas as pd
import pylab
import sklearn as sk
%pylab inline

df = pd.read_csv('card_transdata.csv')

Populating the interactive namespace from numpy and matplotlib


/usr/lib/python3/dist-packages/IPython/core/magics/pylab.py:161: UserWarning: pylab import has clobbered these variables: ['pylab']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [101]:
from sklearn.model_selection import train_test_split

#divide the dataset into train and test data set

#divide target class and the rest of features
X = df.drop("fraud", axis=1)
y = df["fraud"]

#divide the dataset into train and test data set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=22, stratify=y)

In [102]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import recall_score
from sklearn.metrics import confusion_matrix

In [103]:
X[:10]
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 7 columns):
distance_from_home                1000000 non-null float64
distance_from_last_transaction    1000000 non-null float64
ratio_to_median_purchase_price    1000000 non-null float64
repeat_retailer                   1000000 non-null float64
used_chip                         1000000 non-null float64
used_pin_number                   1000000 non-null float64
online_order                      1000000 non-null float64
dtypes: float64(7)
memory usage: 53.4 MB


In [104]:
%%time
# train the MultinomialNB model 
nb_model = MultinomialNB().fit(X_train, y_train)

CPU times: user 115 ms, sys: 7.9 ms, total: 123 ms
Wall time: 123 ms


In [105]:
%%time
# train the DecisionTree model 
dt_model = DecisionTreeClassifier().fit(X_train, y_train)

CPU times: user 1.3 s, sys: 11.1 ms, total: 1.31 s
Wall time: 1.3 s


In [106]:
%%time
# train the RandomForest model 
rf_model = RandomForestClassifier().fit(X_train, y_train)

CPU times: user 4.51 s, sys: 0 ns, total: 4.51 s
Wall time: 4.58 s


In [107]:
%%time
# MultinomialNB model prediction
nb_preds = nb_model.predict(X_test)

CPU times: user 6.19 ms, sys: 0 ns, total: 6.19 ms
Wall time: 5.9 ms


In [108]:
%%time
# MultinomialNB model prediction
dt_preds = dt_model.predict(X_test)

CPU times: user 3.54 ms, sys: 0 ns, total: 3.54 ms
Wall time: 3.29 ms


In [109]:
%%time
# MultinomialNB model prediction
rf_preds = rf_model.predict(X_test)

CPU times: user 65.4 ms, sys: 2.32 ms, total: 67.7 ms
Wall time: 67.7 ms


In [110]:
#recall of each model
nb_recall = recall_score(y_test, nb_preds, pos_label=0)
dt_recall = recall_score(y_test, dt_preds, pos_label=0)
rf_recall = recall_score(y_test, rf_preds, pos_label=0)

print(f"nb_recall = {nb_recall}")
print(f"dt_recall = {dt_recall}")
print(f"rf_recall = {rf_recall}")

nb_recall = 0.9793720105851994
dt_recall = 1.0
rf_recall = 0.9999945211183493


In [111]:
# accuracy of each model
nb_accuracy = nb_model.score(X_test, y_test)
dt_accuracy = dt_model.score(X_test, y_test)
rf_accuracy = rf_model.score(X_test, y_test)

print(f"nb_accuracy = {nb_accuracy}")
print(f"dt_accuracy = {dt_accuracy}")
print(f"rf_accuracy = {rf_accuracy}")

nb_accuracy = 0.91979
dt_accuracy = 0.999975
rf_accuracy = 0.99997


In [116]:
nb_cm = confusion_matrix(y_test, nb_preds)
dt_cm = confusion_matrix(y_test, dt_preds)
rf_cm = confusion_matrix(y_test, rf_preds)

print(f"nb confusion matrix: \n {nb_cm}\n")
print(f"dt confusion matrix: \n {dt_cm}\n")
print(f"rf confusion matrix: \n {rf_cm}\n")

nb confusion matrix: 
 [[178754   3765]
 [ 12277   5204]]

dt confusion matrix: 
 [[182519      0]
 [     5  17476]]

rf confusion matrix: 
 [[182518      1]
 [     5  17476]]



In [113]:
# explain why the data is too accurate?
# decision tree actually look like
# information gain per feature
# finding the evidence 
# visualization PCA ? 
# altair 